# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
 - mkdir $HOME/.checkpoint
 - R -e "install.packages(c('checkpoint', 'knitr'), repos = 'https://cran.rstudio.com')"
 - R -e "checkpoint::checkpoint('2016-09-02',  use.knitr = TRUE)"
