# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false

install:
 - mkdir $HOME/.checkpoint
 - R -e "install.packages(c('checkpoint', 'devtools', 'rmarkdown', 'knitr'), repos = 'https://cran.rstudio.com'); checkpoint::checkpoint("2015-01-10",  auto.install.knitr = TRUE, use.knitr = TRUE")"
