# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
warnings_are_errors: false
install:
 - mkdir $HOME/.checkpoint
 - R -e "install.packages('devtools'); devtools::install_github('benmarwick/checkpointtest')"
 - R -e "install.packages(c('checkpoint', 'rmarkdown', 'knitr', 'testthat'), repos = 'https://cran.rstudio.com'); library(knitr); checkpoint::checkpoint('2015-01-10',  auto.install.knitr = TRUE, use.knitr = TRUE)"
