# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
warnings_are_errors: false

repos:
  MRAN: "https://mran.microsoft.com/snapshot/2016-11-08"
  
install:
 - mkdir $HOME/.checkpoint
 - R -e "install.packages(c('devtools', 'checkpoint', 'rmarkdown', 'knitr', 'testthat'), repos = 'http://cran.revolutionanalytics.com'); devtools::install_github('benmarwick/checkpointtest'); library(knitr); checkpoint::checkpoint('2015-01-10',  auto.install.knitr = TRUE, use.knitr = TRUE)"
